### ISSUE TITLE
high performance bots do not complete the questionnaire 

### ISSUE THREAD

**Issue by mmosleh** [Dallinger/Griduniverse#191]
High performance bots can't proceed beyond the questionnaire and the experiment just waits for them forever.

**Comment by alecpm** [comment]
I think this is fixed by PR #1376. It seems the issue may have been that `HighPerformanceBots` that were recruited via `MultiRecruiter` didn't have the correct `recruiter_id` set, resulting in the wrong `approve_hit` method being called. In any case I've been able to successfully test `HighPerformanceBots` completing `Griduniverse` experiments with and without the `MultiRecruiter`.

**Comment by jessesnyder** [comment]
Merged - closing.
